INSERT IGNORE INTO `INIT_OPTION` SET `ID` = 1, `CODE` = 'SEDE', `DESCRIPTION` = 'Sede electrónica';
INSERT IGNORE INTO `INIT_OPTION` SET `ID` = 2, `CODE` = 'PETICION_DTO', `DESCRIPTION` = 'A petición departamento';
